### ISSUE TITLE
how do i use this api

### ISSUE THREAD

**Issue by sanidhya711** [AniAPI-Team/aniapi-go#2]
is there any proper documentation for this api?

**Comment by Dazorn96** [comment]
Hi,
actually i am working on a new version of the API.
You can find the actual documentation here:
https://github.com/AniAPI-Team/aniapi-go/wiki

Il giorno gio 5 nov 2020 alle ore 18:43 sanidhyajain1 <
notifications@github.com> ha scritto:

**Comment by Dazorn96** [comment]
Hi,
You can find the actual documentation here: https://github.com/AniAPI-Team/aniapi-go/wiki

**Comment by sanidhyajain1** [comment]
oh great!! and thank you for the link to the documentation.
by when do you plan to release the new API?

**Comment by sanidhyajain1** [comment]
i am able to fetch the anime information but i cant fetch the episode info and why is that?
![ani-api](https://user-images.githubusercontent.com/59452778/98319815-94e7a100-2007-11eb-8a8f-250e62f44a1c.PNG)

**Comment by Dazorn96** [comment]
> oh great!! and thank you for the link to the documentation.
> by when do you plan to release the new API?

Probably in early 2021, actually i am working on a new user system with a new scraping algorithm and also migrating to a more modular programming language.

**Comment by Dazorn96** [comment]
> i am able to fetch the anime information but i cant fetch the episode info and why is that?
> ![ani-api](https://user-images.githubusercontent.com/59452778/98319815-94e7a100-2007-11eb-8a8f-250e62f44a1c.PNG)

This is a 404 error, then probably there is no episodes associated with that anime because the scraper is not finding one. This is the big limitation of actual api version. The only thing i can say to you is to wait until new version beta (or alpha) came out :)

**Comment by sanidhyajain1** [comment]
oh so it has information about that anime but no episodes so is there any anime streaming link that this can fetch cause the anime id which i inserted in the link is for highschool dxd and its very famous but it still cant find it...

**Comment by sanidhyajain1** [comment]
> > oh great!! and thank you for the link to the documentation.
> > by when do you plan to release the new API?
> 
> Probably in early 2021, actually i am working on a new user system with a new scraping algorithm and also migrating to a more modular programming language.

i cant wait >_<

**Comment by Dazorn96** [comment]
> oh so it has information about that anime but no episodes so is there any anime streaming link that this can fetch cause the anime id which i inserted in the link is for highschool dxd and its very famous but it still cant find it...

Are you fetching episodes with AniAPI internal anime ID or AnilistID? Because Highschool DxD New has **4660** internal AniAPI ID, **15451** is AnilistID which is not used by the API

**Comment by sanidhyajain1** [comment]
![ty](https://user-images.githubusercontent.com/59452778/98374967-774a2400-2067-11eb-8362-3dfd3e901af0.PNG)
tysm

**Comment by sanidhyajain1** [comment]
btw the example for the episode link dosent work anymore......so can i find a lot of animes on this api?

**Comment by sanidhya711** [comment]
> > oh great!! and thank you for the link to the documentation.
> > by when do you plan to release the new API?
> 
> Probably in early 2021, actually i am working on a new user system with a new scraping algorithm and also migrating to a more modular programming language.

is it ready yet??

**Comment by Dazorn96** [comment]
> > > oh great!! and thank you for the link to the documentation.
> > > by when do you plan to release the new API?
> > 
> > 
> > Probably in early 2021, actually i am working on a new user system with a new scraping algorithm and also migrating to a more modular programming language.
> 
> is it ready yet??

Hi, we are developing it. I don't know how much time this will take... but i think before 2022 it would be ready to use :)

**Comment by sanidhya711** [comment]
oh nice but is there any way that i'll be automatically notified when it is released

**Comment by Dazorn96** [comment]
> oh nice but is there any way that i'll be automatically notified when it is released

Hi, i have no idea on how to automatically notify interested people when the new version will be released.
For sure, you will notice it because this repo will be set as "archived".

I can update you on the dev status... `Anime` and `Episodes` part has been rewritten and actually is working fine. We just need to end the `User` synchronization part, `OAuth` flow and an intuitive website to host API documentation.

**Comment by sanidhya711** [comment]
thank you vey much for updating me on the API status. im very excited for this!!
