### ISSUE TITLE
Getting 404 on all APIs

### ISSUE THREAD

**Issue by ajayamal** [AniAPI-Team/aniapi-go#3]
Hi,
    I am trying to access your APIs but I am getting 404 on all APIs. I tried using example URLs that were provided within the doc. I attached a screenshot 
![Screenshot from 2021-06-28 13-57-57](https://user-images.githubusercontent.com/32792194/123604881-e3f17900-d818-11eb-9a00-908016157221.png)

**Comment by Dazorn96** [comment]
Hi, currently we are working on a newer version of the API.
We will archive this repo (giving the new API version link) once works are done.

The page you are seeing now is just a mock-alhpa version of the new API docs.

**Comment by ajayamal** [comment]
@Dazorn96  Thank you. I am looking forward to the newer version! cheers ;)
